version: '2'
services:
  consul:
    image: consul
    command: consul agent -server -dev -client=0.0.0.0 -ui -bootstrap -log-level warn
    ports:
      - "8500:8500"

  reverse-proxy:
    build: ./reverse-proxy 
    image: reverse-proxy 
    command: traefik --consulCatalog.endpoint=consul:8500
    ports:
      - "8080:8080"
      - "8081:80"
      - "8600:53/udp"
    depends_on:
      - consul
    links:
      - consul
            
  web:
    build: ./web
    ports:
      - "5000"
    environment:
      - SERVICE_TAGS=traefik.enable=true,traefik.frontend.entryPoints=http,traefik.frontend.rule=Host:localhost;PathPrefixStrip:/web
    volumes:
      - .:/code

  flaskapp:
    build: ./flaskapp
    volumes:
      - ./flaskapp:/flaskapp
    ports:
      - "5000"
    environment:
      - SERVICE_TAGS=traefik.enable=true,traefik.frontend.entryPoints=http,traefik.frontend.rule=Host:localhost;PathPrefixStrip:/flask
    links:
      - consul  

  redis:
    build: ./redis
    volumes:
      - ./redis:/redis_config
    tty: true
    ports:
      - "5052:6379"
    links:
      - consul      

  rabbitmq:
    build: ./rabbitmq
    volumes:
      - ./rabbitmq:/rabbitmq_config
    tty: true
    ports:
      - "5050:5672"
      - "5051:15672"
    links:
      - consul      
      
  mongodb:
    build: ./mongodb
    volumes:
      - ./mongodb:/mongod_config
      - ~/data:/var/lib/mongodb
    ports:
      - "27017"
    links:
      - web     
      
  registrator:
    depends_on:
      - consul
    image: gliderlabs/registrator:master
    command: -internal consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    links:
      - consul
